// For this project development
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  // GlobalComponents for Volar
  export interface GlobalComponents {
    ElAffix: typeof import('../packages/sl-design')['ElAffix']
    ElAlert: typeof import('../packages/sl-design')['ElAlert']
    ElAside: typeof import('../packages/sl-design')['ElAside']
    ElAutocomplete: typeof import('../packages/sl-design')['ElAutocomplete']
    ElAvatar: typeof import('../packages/sl-design')['ElAvatar']
    ElBacktop: typeof import('../packages/sl-design')['ElBacktop']
    ElBadge: typeof import('../packages/sl-design')['ElBadge']
    ElBreadcrumb: typeof import('../packages/sl-design')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('../packages/sl-design')['ElBreadcrumbItem']
    ElButton: typeof import('../packages/sl-design')['ElButton']
    ElButtonGroup: typeof import('../packages/sl-design')['ElButtonGroup']
    ElCalendar: typeof import('../packages/sl-design')['ElCalendar']
    ElCard: typeof import('../packages/sl-design')['ElCard']
    ElCarousel: typeof import('../packages/sl-design')['ElCarousel']
    ElCarouselItem: typeof import('../packages/sl-design')['ElCarouselItem']
    ElCascader: typeof import('../packages/sl-design')['ElCascader']
    ElCascaderPanel: typeof import('../packages/sl-design')['ElCascaderPanel']
    ElCheckbox: typeof import('../packages/sl-design')['ElCheckbox']
    ElCheckboxButton: typeof import('../packages/sl-design')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('../packages/sl-design')['ElCheckboxGroup']
    ElCol: typeof import('../packages/sl-design')['ElCol']
    ElCollapse: typeof import('../packages/sl-design')['ElCollapse']
    ElCollapseItem: typeof import('../packages/sl-design')['ElCollapseItem']
    ElCollapseTransition: typeof import('../packages/sl-design')['ElCollapseTransition']
    ElColorPicker: typeof import('../packages/sl-design')['ElColorPicker']
    ElContainer: typeof import('../packages/sl-design')['ElContainer']
    ElConfigProvider: typeof import('../packages/sl-design')['ElConfigProvider']
    ElDatePicker: typeof import('../packages/sl-design')['ElDatePicker']
    ElDialog: typeof import('../packages/sl-design')['ElDialog']
    ElDivider: typeof import('../packages/sl-design')['ElDivider']
    ElDrawer: typeof import('../packages/sl-design')['ElDrawer']
    ElDropdown: typeof import('../packages/sl-design')['ElDropdown']
    ElDropdownItem: typeof import('../packages/sl-design')['ElDropdownItem']
    ElDropdownMenu: typeof import('../packages/sl-design')['ElDropdownMenu']
    ElEmpty: typeof import('../packages/sl-design')['ElEmpty']
    ElFooter: typeof import('../packages/sl-design')['ElFooter']
    ElForm: typeof import('../packages/sl-design')['ElForm']
    ElFormItem: typeof import('../packages/sl-design')['ElFormItem']
    ElHeader: typeof import('../packages/sl-design')['ElHeader']
    ElIcon: typeof import('../packages/sl-design')['ElIcon']
    ElImage: typeof import('../packages/sl-design')['ElImage']
    ElImageViewer: typeof import('../packages/sl-design')['ElImageViewer']
    ElInput: typeof import('../packages/sl-design')['ElInput']
    ElInputNumber: typeof import('../packages/sl-design')['ElInputNumber']
    ElLink: typeof import('../packages/sl-design')['ElLink']
    ElMain: typeof import('../packages/sl-design')['ElMain']
    ElMenu: typeof import('../packages/sl-design')['ElMenu']
    ElMenuItem: typeof import('../packages/sl-design')['ElMenuItem']
    ElMenuItemGroup: typeof import('../packages/sl-design')['ElMenuItemGroup']
    ElOption: typeof import('../packages/sl-design')['ElOption']
    ElOptionGroup: typeof import('../packages/sl-design')['ElOptionGroup']
    ElPageHeader: typeof import('../packages/sl-design')['ElPageHeader']
    ElPagination: typeof import('../packages/sl-design')['ElPagination']
    ElPopconfirm: typeof import('../packages/sl-design')['ElPopconfirm']
    ElPopper: typeof import('../packages/sl-design')['ElPopper']
    ElPopover: typeof import('../packages/sl-design')['ElPopover']
    ElProgress: typeof import('../packages/sl-design')['ElProgress']
    ElRadio: typeof import('../packages/sl-design')['ElRadio']
    ElRadioButton: typeof import('../packages/sl-design')['ElRadioButton']
    ElRadioGroup: typeof import('../packages/sl-design')['ElRadioGroup']
    ElRate: typeof import('../packages/sl-design')['ElRate']
    ElRow: typeof import('../packages/sl-design')['ElRow']
    ElScrollbar: typeof import('../packages/sl-design')['ElScrollbar']
    ElSelect: typeof import('../packages/sl-design')['ElSelect']
    ElSlider: typeof import('../packages/sl-design')['ElSlider']
    ElStep: typeof import('../packages/sl-design')['ElStep']
    ElSteps: typeof import('../packages/sl-design')['ElSteps']
    ElSubMenu: typeof import('../packages/sl-design')['ElSubMenu']
    ElSwitch: typeof import('../packages/sl-design')['ElSwitch']
    ElTabPane: typeof import('../packages/sl-design')['ElTabPane']
    ElTable: typeof import('../packages/sl-design')['ElTable']
    ElTableColumn: typeof import('../packages/sl-design')['ElTableColumn']
    ElTabs: typeof import('../packages/sl-design')['ElTabs']
    ElTag: typeof import('../packages/sl-design')['ElTag']
    ElText: typeof import('../packages/sl-design')['ElText']
    ElTimePicker: typeof import('../packages/sl-design')['ElTimePicker']
    ElTimeSelect: typeof import('../packages/sl-design')['ElTimeSelect']
    ElTimeline: typeof import('../packages/sl-design')['ElTimeline']
    ElTimelineItem: typeof import('../packages/sl-design')['ElTimelineItem']
    ElTooltip: typeof import('../packages/sl-design')['ElTooltip']
    ElTransfer: typeof import('../packages/sl-design')['ElTransfer']
    ElTree: typeof import('../packages/sl-design')['ElTree']
    ElTreeV2: typeof import('../packages/sl-design')['ElTreeV2']
    ElTreeSelect: typeof import('../packages/sl-design')['ElTreeSelect']
    ElUpload: typeof import('../packages/sl-design')['ElUpload']
    ElSpace: typeof import('../packages/sl-design')['ElSpace']
    ElSkeleton: typeof import('../packages/sl-design')['ElSkeleton']
    ElSkeletonItem: typeof import('../packages/sl-design')['ElSkeletonItem']
    ElStatistic: typeof import('../packages/sl-design')['ElStatistic']
    ElCheckTag: typeof import('../packages/sl-design')['ElCheckTag']
    ElDescriptions: typeof import('../packages/sl-design')['ElDescriptions']
    ElDescriptionsItem: typeof import('../packages/sl-design')['ElDescriptionsItem']
    ElResult: typeof import('../packages/sl-design')['ElResult']
    ElSelectV2: typeof import('../packages/sl-design')['ElSelectV2']
    ElWatermark: typeof import('../packages/sl-design')['ElWatermark']
    ElTour: typeof import('../packages/sl-design')['ElTour']
    ElTourStep: typeof import('../packages/sl-design')['ElTourStep']
    ElAnchor: typeof import('../packages/sl-design')['ElAnchor']
    ElAnchorLink: typeof import('../packages/sl-design')['ElAnchorLink']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/sl-design')['ElMessage']
    $notify: typeof import('../packages/sl-design')['ElNotification']
    $msgbox: typeof import('../packages/sl-design')['ElMessageBox']
    $messageBox: typeof import('../packages/sl-design')['ElMessageBox']
    $alert: typeof import('../packages/sl-design')['ElMessageBox']['alert']
    $confirm: typeof import('../packages/sl-design')['ElMessageBox']['confirm']
    $prompt: typeof import('../packages/sl-design')['ElMessageBox']['prompt']
    $loading: typeof import('../packages/sl-design')['ElLoadingService']
  }
}

export {}
