// export const PKG_PREFIX = '@element-plus'
// export const PKG_NAME = 'element-plus'
// export const PKG_CAMELCASE_NAME = 'ElementPlus'
// export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
// export const PKG_BRAND_NAME = 'Element Plus'

export const PKG_PREFIX = '@sl-design/sl-ui'
export const PKG_NAME = 'element-plus'
export const PKG_CAMELCASE_NAME = 'ElementPlus'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementPlusLocale'
export const PKG_BRAND_NAME = 'Element Plus'
